name: Terraform CD - Dev

on:
  workflow_run:
    workflows: ["Terraform CI - Dev"]
    types: [completed]

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  plan-dev:
    uses: Azure-CICD-Labs/Branch-Based-Reusable-Workflows/.github/workflows/tf-plan.yml@main
    name: Plan for Dev
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'dev')
    with:
      environment_name: dev-plan
      plan_filename: dev.tfplan
      artifact_name: terraform-dev-plan
      tfstate_key: branch-based-reusable-workflows.tfstate
      # Use the head SHA of the triggering workflow_run
      checkout_ref: ${{ github.event.workflow_run.head_sha }}
      is_pr: ${{ github.event.workflow_run.event == 'pull_request' }}
    secrets: inherit

  apply-dev:
    uses: Azure-CICD-Labs/Branch-Based-Reusable-Workflows/.github/workflows/tf-apply.yml@main
    name: Apply to Dev
    needs: [plan-dev]
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'dev') &&
      needs.plan-dev.outputs.tfplan_exitcode == '2' &&
      github.event.workflow_run.event == 'push'
    with:
      environment_name: dev-apply
      plan_filename: dev.tfplan
      artifact_name: terraform-dev-plan
      tfstate_key: branch-based-reusable-workflows.tfstate
      checkout_ref: ${{ github.event.workflow_run.head_sha }}
    secrets: inherit
