name: Terraform CD - Prod

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  check_branch:
    name: Check branch
    runs-on: ubuntu-latest
    steps:
      - name: Check if only merging dev -> main
        if: github.base_ref == 'main' && github.head_ref != 'dev'
        run: |
          echo "ERROR: You can only merge to main from dev."
          exit 1

  plan-prod:
    name: Plan for Prod
    needs: [check_branch]
    uses: Azure-CICD-Labs/Branch-Based-Reusable-Workflows/.github/workflows/tf-plan.yml@main
    with:
      environment_name: prod-plan
      plan_filename: prod.tfplan
      artifact_name: terraform-prod-plan
      tfstate_key: branch-based-reusable-workflows.tfstate
      # For pull_request, use the PR head SHA; for push, use github.sha
      checkout_ref: ${{ github.event.pull_request.head.sha || github.sha }}
      is_pr: ${{ github.event_name == 'pull_request' }}
    secrets: inherit

  apply-prod:
    name: Apply to Prod
    needs: [plan-prod]
    uses: Azure-CICD-Labs/Branch-Based-Reusable-Workflows/.github/workflows/tf-apply.yml@main
    if: >
      github.event_name == 'push' &&
      needs.plan-prod.outputs.tfplan_exitcode == '2'
    with:
      environment_name: prod-apply
      plan_filename: prod.tfplan
      artifact_name: terraform-prod-plan
      tfstate_key: branch-based-reusable-workflows.tfstate
      checkout_ref: ${{ github.sha }}
    secrets: inherit