name: Terraform CI - Dev

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

permissions:
  contents: read
  id-token: write

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step – Skipping Terraform CI
        run: echo "Terraform CI job skipped. Exiting successfully."
    # steps:
    #   - name: Check out Repository
    #     uses: actions/checkout@v3

    #   - name: Set up Terraform
    #     uses: hashicorp/setup-terraform@v2
    #     with:
    #       terraform_version: 1.5.6

    #   - name: Install TFLint
    #     run: |
    #       curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    #   - name: Install Checkov
    #     run: |
    #       pip install --upgrade pip
    #       pip install checkov

    #   - name: Format Check
    #     run: terraform fmt -check -recursive

    #   - name: Validate
    #     run: terraform validate

    #   - name: Lint with TFLint
    #     run: tflint --init && tflint

    #   - name: Run Checkov
    #     run: checkov -d .
